### ISSUE TITLE
<workspace_path>/scala/coursier: File Not Found error when running wake runSim arkDUT

### ISSUE THREAD

**Issue by saurabhsingh-pvips** [sifive/block-ark#8]
I have started a workspace with block-ark. I have changed the wit-manifest to include:
` api-generator-sifive::43b6fa2fa2722ea5770bafc738fb035409f5b6e5`
`api-scala-sifive::1c38068e5338dce8594f3aef0466c6333f46a24d`
`soc-testsocket-sifive::466b3f183a1a110ca344017aa3bcc1cb46b66984`

I have created a wake script on similar to how described in `block-pio-sifive` example:
```
global def blockARKSiFiveRoot = simplify "{here}/../.."

global def arkScalaModule =
  def name = "ark"
  def rootDir = "{blockARKSiFiveRoot}/craft/ark"
  def scalaVersion = sifiveSkeletonScalaModule.getScalaModuleScalaVersion
  def deps = sifiveBlocksScalaModule, sifiveSkeletonScalaModule, Nil
  makeScalaModule name rootDir scalaVersion
  | setScalaModuleSourceDirs ("src", Nil)
  | setScalaModuleDeps deps
  | setScalaModuleScalacOptions ("-Xsource:2.11", Nil)

global def arkBlock =
  def scalaModule = arkScalaModule
  def config = "sifive.blocks.ark.WitharkTop"
  makeScalaBlock scalaModule config

global def arkDUT =
  def name = "arkDUT"
  def blocks = arkBlock, Nil
  makeTestSocketDUT name blocks
```
The following error occurs when running command **`wake runSim arkDUT`**:

```
Traceback (most recent call last):
  File "api-scala-sifive/bloop_wake", line 137, in <module>
    main()
  File "api-scala-sifive/bloop_wake", line 124, in main
    if not scalaplugin.run_bloop(coursier, bloop_home, cache, args.bloop_args):
  File "wit/lib/wit/scalaplugin.py", line 63, in run_bloop
    classpath = bloop_classpath(coursier, cache)
  File "wit/lib/wit/scalaplugin.py", line 58, in bloop_classpath
    proc = subprocess.run(cmd, stdout=subprocess.PIPE, universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '<workspace-block-ark_path>/scala/coursier'
'<hash>' build/api-scala-sifive/bloop/chisel3Macros.json
'<hash>' build/chisel3Macros/scala-2.12/jar/chisel3Macros.jar
hash_open: build/chisel3Macros/scala-2.12/jar/chisel3Macros.jar: No such file or directory
Traceback (most recent call last):
  File "api-scala-sifive/bloop_wake", line 137, in <module>
    main()
  File "api-scala-sifive/bloop_wake", line 124, in main
    if not scalaplugin.run_bloop(coursier, bloop_home, cache, args.bloop_args):
  File "wit/lib/wit/scalaplugin.py", line 63, in run_bloop
    classpath = bloop_classpath(coursier, cache)
  File "wit/lib/wit/scalaplugin.py", line 58, in bloop_classpath
    proc = subprocess.run(cmd, stdout=subprocess.PIPE, universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '<workspace-block-ark_path>/scala/coursier
```
Entire log is attached here:
[runSim.log](https://github.com/sifive/block-ark/files/4266336/runSim.log)

**Comment by saurabhsingh-pvips** [comment]
Fixed it with `wit fetch-scala` .
